org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
geckolib_version=4.8.4
cloth_config_version=11.1.136
modmenu_version=7.2.2
emi_version=1.1.24+1.20.1
jade_fabric_version=11.13.1+fabric
jade_forge_version=11.13.2+forge
jei_version=15.48.0.179

enabled_platform=fabric,forge
fabric_loader_version=0.19.3
fabric_api_version=0.92.11+1.20.1
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
forge_version=47.4.10
forge_version_range=[47.4.0,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=saintsdragons
mod_name=Saint's Dragons
mod_license=MIT
mod_version=0.9.88
mod_group_id=com.leon.saintsdragons
mod_authors=Leon Saint
mod_description=Adds animated dragons or wyverns or whatever the heck you wanna call them flying reptiles to Minecraft.
modrinth_project_id=rjcsjwEU
curseforge_project_id=1358098
